# Generated by Django 2.1.2 on 2018-12-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamthi',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kythi',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='phongthi',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='chamthi',
            table='cham_thi',
        ),
        migrations.AlterModelTable(
            name='kythi',
            table='ky_thi',
        ),
        migrations.AlterModelTable(
            name='phongthi',
            table='phong_thi',
        ),
    ]
