# Generated by Django 2.1.2 on 2018-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietlop',
            name='DonVi',
        ),
        migrations.RemoveField(
            model_name='chitietlop',
            name='MaHocVien',
        ),
        migrations.RemoveField(
            model_name='chitietlop',
            name='MaLop',
        ),
        migrations.RemoveField(
            model_name='chitietlop',
            name='Mon',
        ),
        migrations.AlterField(
            model_name='kythi',
            name='KhoaHoc',
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ChiTietLop',
        ),
        migrations.DeleteModel(
            name='LopHoc',
        ),
    ]
