# Generated by Django 2.1.2 on 2018-12-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phongthi',
            name='maLop',
        ),
    ]
