# Generated by Django 2.1.2 on 2018-12-11 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0002_auto_20181211_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='kythi',
            name='NgayThi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nguoi',
            name='NgaySinh',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phongthi',
            name='NgayCham',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
