# Generated by Django 2.1.2 on 2018-12-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0002_remove_phongthi_malop'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongthi',
            name='maLop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoiThi.ChiTietLop'),
        ),
    ]
