# Generated by Django 2.1.2 on 2018-12-19 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0002_auto_20181219_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mon',
            name='MaMon',
        ),
        migrations.RemoveField(
            model_name='mon',
            name='TenMon',
        ),
        migrations.AddField(
            model_name='canbo',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='diem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mon',
            name='maMon',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mon',
            name='tenMon',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='tuoi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='maCanBo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='maDonVi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoiThi.DonVi'),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='quanHam',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='tenCanBo',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chamthi',
            name='canBoCham1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canBoCham1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamthi',
            name='canBoCham2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canBoCham2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamthi',
            name='maPhong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.PhongThi'),
        ),
        migrations.AlterField(
            model_name='chitietkhoa',
            name='maKhoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.KhoaHoc'),
        ),
        migrations.AlterField(
            model_name='chitietkhoa',
            name='maLop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.LopHoc'),
        ),
        migrations.AlterField(
            model_name='chitietlop',
            name='ghiChu',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chitietlop',
            name='lyDo',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chitietlop',
            name='maLop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.LopHoc'),
        ),
        migrations.AlterField(
            model_name='chitietlop',
            name='maSinhVien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.SinhVien'),
        ),
        migrations.AlterField(
            model_name='chitietlop',
            name='trangThai',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donvi',
            name='maDonVi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donvi',
            name='tenDonVi',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='he',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='maKhoaHoc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='tenKhoaHoc',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kythi',
            name='maKyThi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kythi',
            name='tenKyThi',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='maKhoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.KhoaHoc'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='maLop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='maMon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.Mon'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='tenLop',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='canBoCoi1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canBoCoi1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='canBoCoi2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canBoCoi2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='maLop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoiThi.LopHoc'),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='maPhong',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='viTri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='maDonVi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoiThi.DonVi'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='maSinhVien',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='tenSinhVien',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
