# Generated by Django 2.1.2 on 2018-12-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0003_phongthi_malop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kythi',
            name='maKyThi',
        ),
    ]
