# Generated by Django 2.1.2 on 2018-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0004_auto_20181226_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongthi',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='phongthi',
            name='thoiGianThi',
            field=models.IntegerField(default=0),
        ),
    ]
