# Generated by Django 2.1.2 on 2018-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0005_auto_20181226_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='hinhThucThi',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
