# Generated by Django 2.1.2 on 2018-12-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0005_auto_20181221_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phongthi',
            name='maPhong',
        ),
        migrations.AddField(
            model_name='phongthi',
            name='tenPhong',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
