# Generated by Django 2.1.1 on 2018-12-26 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0005_auto_20181221_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phongthi',
            name='maPhong',
        ),
        migrations.AddField(
            model_name='phongthi',
            name='tenPhong',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='maLop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoiThi.LopHoc'),
        ),
    ]
