# Generated by Django 2.1.1 on 2018-12-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0006_auto_20181226_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phongthi',
            name='maLop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoiThi.ChiTietLop'),
        ),
    ]
