# Generated by Django 2.1.2 on 2019-01-04 08:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0008_auto_20181227_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='tuoi',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='ngaySinh',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.date(2019, 1, 4)),
            preserve_default=False,
        ),
    ]
