# Generated by Django 2.1.2 on 2019-01-07 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0009_auto_20190104_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietlop',
            name='soBaoDanh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ngaySinh',
            field=models.DateField(verbose_name=datetime.date(2019, 1, 7)),
        ),
    ]
