# Generated by Django 2.1.2 on 2019-01-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0010_auto_20190107_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='DapAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDe', models.CharField(max_length=100, null=True)),
                ('dapAn', models.FileField(upload_to='DapAn')),
            ],
            options={
                'db_table': 'dap_an',
                'managed': True,
            },
        ),
    ]
