# Generated by Django 2.1.7 on 2019-03-10 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0013_baithi_made'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaiThi',
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='baiLam',
            field=models.FileField(null=True, upload_to='BaiLam'),
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='maDe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dapan',
            name='makithi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoiThi.KyThi'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ngaySinh',
            field=models.DateField(verbose_name=datetime.date(2019, 3, 10)),
        ),
    ]
