# Generated by Django 2.1.7 on 2019-03-17 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0015_auto_20190311_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_diem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemCu', models.IntegerField(default=0)),
                ('diemMoi', models.IntegerField(default=0)),
                ('ngaySua', models.DateField(default=django.utils.timezone.now)),
                ('lyDoSua', models.TextField(max_length=300, null=True)),
                ('nguoiSua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoisua', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_diem',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='maPhach',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ngaySinh',
            field=models.DateField(verbose_name=datetime.date(2019, 3, 17)),
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='log_sua_diem',
            field=models.ManyToManyField(db_table='log_sua_diem', related_name='log_sua_diem', to='CoiThi.Log_diem'),
        ),
    ]
