# Generated by Django 2.1.7 on 2019-03-19 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0016_auto_20190317_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietlop',
            name='diem',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ngaySinh',
            field=models.DateField(verbose_name=datetime.date(2019, 3, 19)),
        ),
    ]
