# Generated by Django 2.1.7 on 2019-04-26 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0018_auto_20190319_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_diem',
            name='ngaySua',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ngaySinh',
            field=models.DateField(verbose_name=datetime.date(2019, 4, 26)),
        ),
    ]
