# Generated by Django 2.1.7 on 2019-04-26 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0019_auto_20190426_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_diem',
            name='ngaySua',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
