# Generated by Django 2.1.7 on 2019-04-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoiThi', '0020_auto_20190426_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_diem',
            name='ngaySua',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
